# Generated by Django 5.1.11 on 2025-07-06 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Tiêu đề cuộc bầu cử"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Thời gian bắt đầu")),
                ("end_date", models.DateTimeField(verbose_name="Thời gian kết thúc")),
            ],
            options={
                "verbose_name": "Cuộc Bầu Cử",
                "verbose_name_plural": "Các Cuộc Bầu Cử",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Hash Khối Trước",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Dấu thời gian"
                    ),
                ),
                ("difficulty", models.IntegerField(verbose_name="Độ khó")),
                ("nonce", models.BigIntegerField(default=0, verbose_name="Nonce")),
                (
                    "hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Hash",
                    ),
                ),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanly.ballot",
                        verbose_name="Cuộc bầu cử",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khối",
                "verbose_name_plural": "Các Khối",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên ứng viên")),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanly.ballot",
                        verbose_name="Cuộc bầu cử",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ứng Viên",
                "verbose_name_plural": "Các Ứng Viên",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_public_key",
                    models.TextField(verbose_name="Khóa công khai của cử tri"),
                ),
                ("signature", models.TextField(verbose_name="Chữ ký số")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Dấu thời gian"
                    ),
                ),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanly.ballot",
                        verbose_name="Cuộc bầu cử",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="quanly.block",
                        verbose_name="Thuộc khối",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanly.candidate",
                        verbose_name="Ứng viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu Bầu (Vote)",
                "verbose_name_plural": "Các Phiếu Bầu (Votes)",
            },
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(unique=True, verbose_name="Khóa công khai"),
                ),
                (
                    "private_key_encrypted",
                    models.TextField(verbose_name="Khóa bí mật đã mã hóa"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cử Tri",
                "verbose_name_plural": "Các Cử Tri",
            },
        ),
    ]
