# Generated by Django 5.1.11 on 2025-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Ảnh đại diện"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="description",
            field=models.TextField(blank=True, verbose_name="Mô tả"),
        ),
    ]
