# Generated by Django 5.1.11 on 2025-07-06 10:39

import quanly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0002_candidate_avatar_candidate_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=quanly.models.candidate_avatar_path,
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
