# Generated by Django 5.1.11 on 2025-07-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0004_voter_salt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="private_key_encrypted",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="salt",
        ),
    ]
