# Generated by Django 5.2.4 on 2025-07-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0005_remove_voter_private_key_encrypted_remove_voter_salt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTamperLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_candidate_name",
                    models.CharField(max_length=255, verbose_name="Ứng viên gốc"),
                ),
                (
                    "new_candidate_name_attempt",
                    models.CharField(
                        max_length=255, verbose_name="Ứng viên định thay đổi thành"
                    ),
                ),
                ("description", models.TextField(verbose_name="Mô tả hành vi")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Địa chỉ IP"
                    ),
                ),
                (
                    "attempted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
                (
                    "vote_tampered",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quanly.vote",
                        verbose_name="Phiếu bầu bị tác động",
                    ),
                ),
            ],
        ),
    ]
