# Generated by Django 5.2.4 on 2025-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0006_usertamperlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertamperlog",
            options={
                "verbose_name": "Lịch Sử Sửa Phiếu",
                "verbose_name_plural": "Các Lịch Sử Sửa Phiếu",
            },
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="user_agent",
            field=models.TextField(
                blank=True, null=True, verbose_name="Thông tin Trình duyệt"
            ),
        ),
    ]
