# Generated by Django 5.2.4 on 2025-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0007_alter_usertamperlog_options_usertamperlog_user_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertamperlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="browser",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Trình duyệt"
            ),
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="device",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Thiết bị"
            ),
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="os",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Hệ điều hành"
            ),
        ),
    ]
