# Generated by Django 5.2.4 on 2025-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0008_remove_usertamperlog_user_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertamperlog",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Vĩ độ"),
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Kinh độ"),
        ),
    ]
