# Generated by Django 5.1.11 on 2025-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0009_usertamperlog_latitude_usertamperlog_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="eligible_voters",
            field=models.ManyToManyField(
                blank=True,
                related_name="private_ballots",
                to="quanly.voter",
                verbose_name="Cử tri được phép (cho bầu cử riêng tư)",
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="type",
            field=models.CharField(
                choices=[("PUBLIC", "Công khai"), ("PRIVATE", "Riêng tư")],
                default="PUBLIC",
                max_length=10,
                verbose_name="Loại hình",
            ),
        ),
    ]
