# Generated by Django 5.1.11 on 2025-08-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0010_ballot_eligible_voters_ballot_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertamperlog",
            name="backup_file_path",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Đường dẫn file backup",
            ),
        ),
    ]
