# Generated by Django 5.1.11 on 2025-08-04 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0011_usertamperlog_backup_file_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertamperlog",
            name="browser",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="device",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="new_candidate_name_attempt",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="original_candidate_name",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="os",
        ),
        migrations.RemoveField(
            model_name="usertamperlog",
            name="vote_tampered",
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="ballot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="quanly.ballot",
                verbose_name="Cuộc bầu cử liên quan",
            ),
        ),
        migrations.AddField(
            model_name="usertamperlog",
            name="details",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Chi tiết thay đổi"
            ),
        ),
        migrations.AlterField(
            model_name="usertamperlog",
            name="attempted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người thực hiện",
            ),
        ),
        migrations.AlterField(
            model_name="usertamperlog",
            name="description",
            field=models.TextField(verbose_name="Mô tả chi tiết sự việc"),
        ),
        migrations.AlterField(
            model_name="usertamperlog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời gian phát hiện"
            ),
        ),
    ]
