# Generated by Django 5.1.11 on 2025-08-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0012_remove_usertamperlog_browser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="voter_public_key",
        ),
    ]
