# Generated by Django 5.1.11 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0013_remove_vote_voter_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="voter_public_key",
            field=models.TextField(
                default="", verbose_name="Khóa công khai của cử tri"
            ),
            preserve_default=False,
        ),
    ]
