# Generated by Django 5.1.11 on 2025-08-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0014_vote_voter_public_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="candidate",
        ),
        migrations.AddField(
            model_name="ballot",
            name="max_choices",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vote",
            name="candidates",
            field=models.ManyToManyField(
                to="quanly.candidate", verbose_name="Các ứng viên đã bầu"
            ),
        ),
    ]
