# Generated by Django 5.1.11 on 2025-08-06 08:51

from django.db import migrations

APPLY_TRIGGERS_SQL = """
-- Triggers cho bảng quanly_vote
CREATE TRIGGER check_vote_immutability_update
BEFORE UPDATE ON quanly_vote
BEGIN
    SELECT RAISE(ABORT, 'Hành động SỬA không được phép trên bảng này để đảm bảo tính bất biến.');
END;

CREATE TRIGGER check_vote_immutability_delete
BEFORE DELETE ON quanly_vote
BEGIN
    SELECT RAISE(ABORT, 'Hành động XÓA không được phép trên bảng này để đảm bảo tính bất biến.');
END;

-- Triggers cho bảng quanly_block
CREATE TRIGGER check_block_immutability_update
BEFORE UPDATE ON quanly_block
BEGIN
    SELECT RAISE(ABORT, 'Hành động SỬA không được phép trên bảng này để đảm bảo tính bất biến.');
END;

CREATE TRIGGER check_block_immutability_delete
BEFORE DELETE ON quanly_block
BEGIN
    SELECT RAISE(ABORT, 'Hành động XÓA không được phép trên bảng này để đảm bảo tính bất biến.');
END;
"""

# SQL để xóa các trigger (cần cho việc rollback)
DROP_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS check_vote_immutability_update;
DROP TRIGGER IF EXISTS check_vote_immutability_delete;
DROP TRIGGER IF EXISTS check_block_immutability_update;
DROP TRIGGER IF EXISTS check_block_immutability_delete;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0015_remove_vote_candidate_ballot_max_choices_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=APPLY_TRIGGERS_SQL,
            reverse_sql=DROP_TRIGGERS_SQL
        ),
    ]

