# Generated by Django 5.1.11 on 2025-08-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0016_enforce_immutability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="block",
        ),
        migrations.DeleteModel(
            name="Block",
        ),
    ]
