# Generated by Django 5.1.11 on 2025-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0017_remove_vote_block_delete_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="candidates",
        ),
        migrations.AddField(
            model_name="vote",
            name="encrypted_vote_data",
            field=models.TextField(
                default="", verbose_name="Dữ liệu phiếu bầu đã mã hóa"
            ),
            preserve_default=False,
        ),
    ]
