# Generated by Django 5.1.11 on 2025-08-07 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0018_remove_vote_candidates_vote_encrypted_vote_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="council_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="councils",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Thành viên Hội đồng Kiểm phiếu",
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="threshold",
            field=models.IntegerField(
                default=2,
                help_text="Số lượng thành viên tối thiểu cần thiết để giải mã phiếu bầu.",
                verbose_name="Ngưỡng giải mã",
            ),
        ),
    ]
