# Generated by Django 5.1.11 on 2025-08-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0019_ballot_council_members_ballot_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="council_public_key",
            field=models.TextField(
                blank=True, null=True, verbose_name="Khóa Công khai Hội đồng"
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="key_shares_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Các mảnh khóa bí mật"
            ),
        ),
    ]
