# Generated by Django 5.1.11 on 2025-08-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0020_ballot_council_public_key_ballot_key_shares_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ballot",
            name="key_shares_json",
        ),
    ]
