# Generated by Django 5.2.5 on 2025-08-07 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0021_remove_ballot_key_shares_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmittedKeyShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_share", models.TextField(verbose_name="Mảnh khóa bí mật đã nộp")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_shares",
                        to="quanly.ballot",
                    ),
                ),
                (
                    "council_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mảnh khóa Đã nộp",
                "verbose_name_plural": "Các Mảnh khóa Đã nộp",
                "unique_together": {("ballot", "council_member")},
            },
        ),
    ]
