# Generated by Django 5.2.5 on 2025-08-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quanly", "0022_submittedkeyshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="candidates",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="quanly.candidate",
                verbose_name="Các ứng viên đã bầu",
            ),
        ),
    ]
